

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][15][49][15]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][15][53][17]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][16][0 ][46]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 198, in on_event
    chunkprovider.world[previous].blocksettedto = block
KeyError: (0, -1, 0)
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 758, in _event_raw_input
    self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][3 ][59]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][18][33]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][19][37]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][21][18]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][21][47]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][42][38]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][16][43][59]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 75, in on_event
    G.chat.on_key_press(symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 52, in on_key_press
    self.execute(self.text)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 88, in execute
    G.commandhandler.executeCommand(command, G.player.entity, G.window.position)
  File "C:\Python\mcpython\mcpython_7\command\Command.py", line 14, in executeCommand
    command.executeCommand(line, entity, position)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 37, in executeCommand
    copyair=copyair, middlerelative=arrayint(basepos))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\stucture.py", line 50, in load_out_of_world
    if (x, y, z) in G.model.world:
AttributeError: 'Model' object has no attribute 'world'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 710, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 309, in on_key_press
    G.eventhandler.call("core:window:on_key_press", symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][44][59]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][16][46][5 ]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 75, in on_event
    G.chat.on_key_press(symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 52, in on_key_press
    self.execute(self.text)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 88, in execute
    G.commandhandler.executeCommand(command, G.player.entity, G.window.position)
  File "C:\Python\mcpython\mcpython_7\command\Command.py", line 14, in executeCommand
    command.executeCommand(line, entity, position)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 37, in executeCommand
    copyair=copyair, middlerelative=arrayint(basepos))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\stucture.py", line 51, in load_out_of_world
    if (x, y, z) in G.model.world:
AttributeError: 'Model' object has no attribute 'world'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 710, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 309, in on_key_press
    G.eventhandler.call("core:window:on_key_press", symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][16][46][38]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][15][45]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][16][4 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][19][0 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][23][10]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][24][6 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][24][59]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][25][54]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][27][0 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][27][27]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][28][31]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][29][45]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][29][58]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][30][36]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][31][15]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][31][53]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][32][34]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][33][11]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][34][27]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][36][24]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][37][30]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][17][37][53]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\world\model.py", line 42, in _initialize
    G.dimensionhandler.prepare()
  File "C:\Python\mcpython\mcpython_7\world\Dimensions.py", line 23, in prepare
    dim.prepare()
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\plugins\vanilla.py", line 82, in prepare
    self.worldgenerator.generateSurfaceToChunkProvider((cx, cz))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\WorldGenerator.py", line 111, in generateSurfaceToChunkProvider
    r = random.randint(1, round(1/structure.getPlaceChance()))
AttributeError: 'NoneType' object has no attribute 'getPlaceChance'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 891, in _event_lbuttondown
    'on_mouse_press', mouse.LEFT, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 884, in _event_mousebutton
    self.dispatch_event(ev, x, y, button, self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 41, in on_event
    G.eventhandler.call("worldgen:newworld")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][39][35]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][17][39][50]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\world\model.py", line 42, in _initialize
    G.dimensionhandler.prepare()
  File "C:\Python\mcpython\mcpython_7\world\Dimensions.py", line 23, in prepare
    dim.prepare()
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\plugins\vanilla.py", line 82, in prepare
    self.worldgenerator.generateSurfaceToChunkProvider((cx, cz))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\WorldGenerator.py", line 113, in generateSurfaceToChunkProvider
    structure.paste(x, high+1, z, chunkprovider)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\decoration\StructureDecoration.py", line 17, in paste
    self.structure.paste_chunkprovider_gen((x, y, z), chunkprovider)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\stucture.py", line 44, in paste_chunkprovider_gen
    nposition = nposition[0] + bx, nposition[1] + by, nposition[2] + bz
TypeError: can only concatenate str (not "int") to str
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 891, in _event_lbuttondown
    'on_mouse_press', mouse.LEFT, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 884, in _event_mousebutton
    self.dispatch_event(ev, x, y, button, self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 41, in on_event
    G.eventhandler.call("worldgen:newworld")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][40][26]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][41][38]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][42][39]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][47][17]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][53][8 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][17][53][19]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][19]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][19]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][19]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][20]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 991, in _event_syscommand
    app.event_loop.enter_blocking()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 236, in enter_blocking
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][20]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 149, in _timer_proc_func
    self._timer_func()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 246, in _blocking_timer
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][20]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][20]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][20]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][21]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][21]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][21]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 991, in _event_syscommand
    app.event_loop.enter_blocking()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 236, in enter_blocking
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][21]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 645, in f
    result = _user32.DefWindowProcW(hwnd, msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 149, in _timer_proc_func
    self._timer_func()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 246, in _blocking_timer
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][21]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][22]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][22]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][22]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][53][22]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 21, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 261, in draw_label
    len(G.player.dimension.worldprovider.chunkproviders))
AttributeError: 'NoneType' object has no attribute 'worldprovider'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][54][5 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][17][55][8 ]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 40, in on_event
    self.draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][55][9 ]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 40, in on_event
    self.draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][55][9 ]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 40, in on_event
    self.draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][55][10]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 40, in on_event
    self.draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][55][10]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\escapemenu.py", line 40, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][17][55][11]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\escapemenu.py", line 40, in on_event
    G.statehandler.states["minecraft:game"].draw_label()
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 265, in draw_label
    self.label1 += "; looking at: "+str(block)
TypeError: unsupported operand type(s) for +=: 'Label' and 'str'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 375, in on_draw
    G.eventhandler.call("opengl:draw2d")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][17][55][28]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][17][59][53]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 75, in on_event
    G.chat.on_key_press(symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 52, in on_key_press
    self.execute(self.text)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 88, in execute
    G.commandhandler.executeCommand(command, G.player.entity, G.window.position)
  File "C:\Python\mcpython\mcpython_7\command\Command.py", line 14, in executeCommand
    command.executeCommand(line, entity, position)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 38, in executeCommand
    copyair=copyair, middlerelative=basepos)
TypeError: load_out_of_world() got an unexpected keyword argument 'middlerelative'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 710, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 309, in on_key_press
    G.eventhandler.call("core:window:on_key_press", symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][18][0 ][20]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][18][1 ][1 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][18][5 ][4 ]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 75, in on_event
    G.chat.on_key_press(symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 52, in on_key_press
    self.execute(self.text)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 88, in execute
    G.commandhandler.executeCommand(command, G.player.entity, G.window.position)
  File "C:\Python\mcpython\mcpython_7\command\Command.py", line 14, in executeCommand
    command.executeCommand(line, entity, position)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 38, in executeCommand
    copyair=copyair, middle=basepos)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\stucture.py", line 66, in load_out_of_world
    else: middlerelative = (middle[0]-sx, middle[1]-sy, middle[2]-sz)
IndexError: list index out of range
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 710, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 309, in on_key_press
    G.eventhandler.call("core:window:on_key_press", symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)

stamp: [2019][3 ][2 ][18][5 ][15]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\game.py", line 75, in on_event
    G.chat.on_key_press(symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 52, in on_key_press
    self.execute(self.text)
  File "C:\Python\mcpython\mcpython_7\chat.py", line 88, in execute
    G.commandhandler.executeCommand(command, G.player.entity, G.window.position)
  File "C:\Python\mcpython\mcpython_7\command\Command.py", line 14, in executeCommand
    command.executeCommand(line, entity, position)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 34, in executeCommand
    basepos = arrayint(basepos)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 7, in arrayint
    return [int(x) for x in array]
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\commands\structure.py", line 7, in <listcomp>
    return [int(x) for x in array]
ValueError: invalid literal for int() with base 10: ''
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 710, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 309, in on_key_press
    G.eventhandler.call("core:window:on_key_press", symbol, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][18][6 ][49]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][18][7 ][34]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][18][9 ][22]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][22][15]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][24][32]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][25][55]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][26][2 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][28][44]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][31][13]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][33][13]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][34][45]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][42][53]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][20][47][27]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][2 ][25]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][21][2 ][41]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\world\model.py", line 42, in _initialize
    G.dimensionhandler.prepare()
  File "C:\Python\mcpython\mcpython_7\world\Dimensions.py", line 23, in prepare
    dim.prepare()
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\plugins\vanilla.py", line 82, in prepare
    self.worldgenerator.generateSurfaceToChunkProvider((cx, cz))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\WorldGenerator.py", line 111, in generateSurfaceToChunkProvider
    r = random.randint(1, round(1/structure.getPlaceChance()))
TypeError: getPlaceChance() missing 1 required positional argument: 'self'
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 891, in _event_lbuttondown
    'on_mouse_press', mouse.LEFT, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 884, in _event_mousebutton
    self.dispatch_event(ev, x, y, button, self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 41, in on_event
    G.eventhandler.call("worldgen:newworld")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][3 ][27]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][21][3 ][48]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\world\model.py", line 42, in _initialize
    G.dimensionhandler.prepare()
  File "C:\Python\mcpython\mcpython_7\world\Dimensions.py", line 23, in prepare
    dim.prepare()
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\plugins\vanilla.py", line 82, in prepare
    self.worldgenerator.generateSurfaceToChunkProvider((cx, cz))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\WorldGenerator.py", line 111, in generateSurfaceToChunkProvider
    r = random.randint(1, round(1/structure.getPlaceChance()))
ZeroDivisionError: division by zero
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 891, in _event_lbuttondown
    'on_mouse_press', mouse.LEFT, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 884, in _event_mousebutton
    self.dispatch_event(ev, x, y, button, self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 41, in on_event
    G.eventhandler.call("worldgen:newworld")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][4 ][19]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][5 ][1 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][6 ][0 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2
stamp: [2019][3 ][2 ][21][6 ][17]
an exception occured

called via:Traceback (most recent call last):
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\world\model.py", line 42, in _initialize
    G.dimensionhandler.prepare()
  File "C:\Python\mcpython\mcpython_7\world\Dimensions.py", line 23, in prepare
    dim.prepare()
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\plugins\vanilla.py", line 82, in prepare
    self.worldgenerator.generateSurfaceToChunkProvider((cx, cz))
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\WorldGenerator.py", line 114, in generateSurfaceToChunkProvider
    structure.paste(x, high+1, z, chunkprovider, cache=True)
  File "C:\Python\mcpython\mcpython_7_mods\mods\BiomesOPlenty\gen\decoration\tree\ITreeDecoration.py", line 23, in paste
    size = self.getLeaveSizeAtHigh(dy, x, z, lshigh, high, lshigh)
TypeError: getLeaveSizeAtHigh() takes 6 positional arguments but 7 were given
  File "C:/Python/mcpython/mcpython_7/main.py", line 120, in <module>
    main()
  File "C:/Python/mcpython/mcpython_7/main.py", line 111, in main
    pyglet.app.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 639, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 891, in _event_lbuttondown
    'on_mouse_press', mouse.LEFT, lParam)
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\win32\__init__.py", line 884, in _event_mousebutton
    self.dispatch_event(ev, x, y, button, self._get_modifiers())
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python\interpretter\Python37-32_1\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python\mcpython\mcpython_7\window.py", line 278, in on_mouse_press
    G.eventhandler.call("core:window:on_mouse_press", x, y, button, modifiers)
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 91, in call
    self.functions[e][0](name, *list(self.functions[e][2])+list(args), **kwargs)
  File "C:\Python\mcpython\mcpython_7\state\titlescreen.py", line 41, in on_event
    G.eventhandler.call("worldgen:newworld")
  File "C:\Python\mcpython\mcpython_7\eventhandler.py", line 93, in call
    exceptionhandler.add_traceback()
  File "C:\Python\mcpython\mcpython_7\exceptionhandler.py", line 45, in add_traceback
    traceback.print_stack(file=f)


--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][6 ][59]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][7 ][23]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][7 ][37]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][2 ][21][8 ][51]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][9 ][49][0 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][9 ][53][23]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][9 ][55][41]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][9 ][55][57]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][20][47][29]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][20][48][1 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2

--------------------------------------------------------------------------------
- MCPYTHON VERSION 19W09B                                                      -
--------------------------------------------------------------------------------
informations about os, location, version etc.
:timestamp | [2019][3 ][3 ][20][49][9 ]
:versionid | 2019091
:G.local | C:/Python/mcpython/mcpython_7
:os name | Windows
:os version | 10.0.17763
:os proccessor | AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
:os proccessor architektur | ('32bit', 'WindowsPE')
:pyglet | 1.3.2